---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: second-app-bar
  namespace: argocd # namespace for the argocd app
  finalizers:
    - resources-finalizer.argocd.argoproj.io # delete K8s app when this resource Application will be deleted
spec:
  project: default # logical grouping of applications, useful when argocd is used by multiple teams
  source:
    repoURL: https://github.com/iurie-bogdanovici/argocd-demo-2.git # repo where our kubernetes manifests are located
    targetRevision: HEAD # points to the main branch
    path: environments/staging/second-app # path to track inside the github repo
  destination:
    server: https://kubernetes.default.svc # useful when you use one argocd instance to deploy to multiple K8s clusters
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
